### ISSUE TITLE
Figure out whether images should be stored and processed by this script or loaded dynamically in the frontend

### ISSUE THREAD

**Issue by ErikThorsell** [ErikThorsell/coffee_roaster_scrapers#33]
**Background** 

The current implementation of the [Coffee Item](https://github.com/ErikThorsell/coffee_roaster_scrapers/blob/main/src/coffee_roaster_scrapers/items.py) uses a URL to reference the image to be displayed of the coffee. ([Example for Gringo.](https://github.com/ErikThorsell/coffee_roaster_scrapers/blob/main/src/coffee_roaster_scrapers/spiders/gringo_spider.py#L65)) 

When developing the frontend, I realized that the different roasters use different images sizes (to be expected) but I was not able to get the HTML code to show the image in the size I wanted. Basically the `width` property did not change the dimensions of the image, only how much of the image was shown. I did not troubleshoot this extensively, but instead opted to download some images and include them in the `public/` directory, in the frontend.

**Problem**

We need to figure out whether it is best to:
1. download the images _while scraping_ and post-process them into the correct dimensions and format, or;
2. dynamically link to the coffee roasters' webpages and fix the image size in the Svelte app, or;
3. something else.

(2) is quite nice, because then we don't need to store and process images offline, but (1) gives more control? (1) also ensures the Coffee Archive (is `kaffearkivet.se` a good name?) will be able to display images even if the roasters' webpages are unavailable. _(Could this be alleviated with a cache?)_

**Acceptance Criteria**

A solution to the problem is presented and a follow-up-issue is created to implement the solution.

**Comment by Jassob** [comment]
I think we should go with option 2. That way we don't have to do the cleaning ourselves and if the roasters have reasonable caching instructions we can piggy-back on that to make page loads quick for us :)

**Comment by ErikThorsell** [comment]
@Jassob, as I wrote above, I'm a bit worried about the risk of downtime on the coffee pages' part; but maybe I'm trying to fix a problem that's not there... Let's go for (2)!

Before we close this issue, I think we should look around and see if there's a good library (or native support) for this functionality. I did a 60 second search and seem to only find libraries with support for images stored in the _public/_ directory, nothing that supported dynamically loading images from other sources.

**Comment by Jassob** [comment]
> @Jassob, as I wrote above, I'm a bit worried about the risk of downtime on the coffee pages' part; but maybe I'm trying to fix a problem that's not there... Let's go for (2)!

I think that is a non-issue TBH, and even if it were the case that would mean that the roaster would be down or something like that (which we might want to handle anyway). Also, if this turns out to be a real problem we can fix it then.

> Before we close this issue, I think we should look around and see if there's a good library (or native support) for this functionality. I did a 60 second search and seem to only find libraries with support for images stored in the _public/_ directory, nothing that supported dynamically loading images from other sources.

Do you mean that the image size should be a fixed size so that the grid is uniform? Because that is easily solved with HTML/CSS and setting the `width` and `height` properties in the style.

Or do you mean that the actual file size would be a problem?

**Comment by ErikThorsell** [comment]
> I think that is a non-issue TBH, and even if it were the case that would mean that the roaster would be down or something like that (which we might want to handle anyway). Also, if this turns out to be a real problem we can fix it then.

I agree!

> Do you mean that the image size should be a fixed size so that the grid is uniform? Because that is easily solved with HTML/CSS and setting the width and height properties in the style.

This. My original solution tried to do this with CSS, but it cropped the image instead of scaling it. I'm not bothered about the file size, yet.
